import icons_rc
from PyQt5 import QtCore, QtGui, QtWidgets
from xlrd import *
from xlsxwriter import *
from PyQt5.QtPrintSupport import QPrintDialog, QPrinter
import os
import sys
import sqlite3
import datetime
from PyQt5.QtPrintSupport import QPrintDialog, QPrinter
from PyQt5.QtWidgets import *

class Mainapp(QMainWindow,object):
    db = sqlite3.connect('ohms.db')
    cur = db.cursor()
    try:
        os.mkdir("C:/Exported file")
    except FileExistsError:
        pass
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 900)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 210, 75, 61))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 390, 75, 61))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/authentication.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 480, 75, 61))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(110, 0, 1181, 681))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(4, 170, 1161, 431))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(770, 130, 191, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(370, 40, 141, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(370, 100, 81, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab)
        self.pushButton_27.setGeometry(QtCore.QRect(420, 610, 321, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(420, 140, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(770, 20, 361, 101))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setGeometry(QtCore.QRect(380, 0, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab)
        self.pushButton_30.setGeometry(QtCore.QRect(980, 130, 151, 31))
        self.pushButton_30.setObjectName("pushButton_30")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(511, 101, 171, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100000)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 110, 171, 31))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(100000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.label_38.setObjectName("label_38")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 0, 1161, 651))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 10, 1141, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(7)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_28.setGeometry(QtCore.QRect(890, 580, 231, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(809, 90, 321, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 60, 291, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(810, 150, 321, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_4.setGeometry(QtCore.QRect(810, 210, 321, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_5.setGeometry(QtCore.QRect(810, 270, 331, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(810, 330, 321, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(560, 480, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(680, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(680, 330, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(680, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(680, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(680, 270, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(20, 160, 411, 251))
        self.textEdit.setObjectName("textEdit")
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        self.label_37.setGeometry(QtCore.QRect(140, 130, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_6.setGeometry(QtCore.QRect(821, 200, 281, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(690, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_7.setGeometry(QtCore.QRect(821, 260, 281, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(890, 470, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 100, 331, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(820, 140, 281, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(690, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_8.setGeometry(QtCore.QRect(821, 320, 281, 31))
        self.comboBox_8.setObjectName("comboBox_8")
        self.label_11 = QtWidgets.QLabel(self.tab_6)
        self.label_11.setGeometry(QtCore.QRect(690, 380, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(690, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(690, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(821, 380, 281, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(30, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(840, 40, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(30, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 30, 331, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 190, 451, 221))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setGeometry(QtCore.QRect(160, 160, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 1171, 651))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 10, 1151, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(7)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_29.setGeometry(QtCore.QRect(910, 580, 241, 31))
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_23.setGeometry(QtCore.QRect(210, 60, 301, 31))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_22.setGeometry(QtCore.QRect(530, 450, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_31 = QtWidgets.QLabel(self.tab_13)
        self.label_31.setGeometry(QtCore.QRect(30, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_24.setGeometry(QtCore.QRect(210, 170, 301, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_32 = QtWidgets.QLabel(self.tab_13)
        self.label_32.setGeometry(QtCore.QRect(30, 170, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_29.setGeometry(QtCore.QRect(210, 280, 301, 31))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_33 = QtWidgets.QLabel(self.tab_13)
        self.label_33.setGeometry(QtCore.QRect(30, 280, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_38.setGeometry(QtCore.QRect(840, 60, 301, 31))
        self.lineEdit_38.setText("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_46 = QtWidgets.QLabel(self.tab_13)
        self.label_46.setGeometry(QtCore.QRect(660, 60, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_13)
        self.label_47.setGeometry(QtCore.QRect(660, 170, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_39.setGeometry(QtCore.QRect(840, 170, 301, 31))
        self.lineEdit_39.setText("")
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_48 = QtWidgets.QLabel(self.tab_13)
        self.label_48.setGeometry(QtCore.QRect(660, 280, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_40.setGeometry(QtCore.QRect(840, 280, 301, 31))
        self.lineEdit_40.setText("")
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_25.setGeometry(QtCore.QRect(770, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_43 = QtWidgets.QLabel(self.tab_14)
        self.label_43.setGeometry(QtCore.QRect(20, 19, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_28.setGeometry(QtCore.QRect(200, 20, 301, 31))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_30.setGeometry(QtCore.QRect(200, 360, 301, 31))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_23.setGeometry(QtCore.QRect(820, 490, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_34 = QtWidgets.QLabel(self.tab_14)
        self.label_34.setGeometry(QtCore.QRect(20, 360, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_14)
        self.label_35.setGeometry(QtCore.QRect(20, 240, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_22.setGeometry(QtCore.QRect(200, 110, 301, 31))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_26.setGeometry(QtCore.QRect(200, 240, 301, 31))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_36 = QtWidgets.QLabel(self.tab_14)
        self.label_36.setGeometry(QtCore.QRect(20, 110, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_24.setGeometry(QtCore.QRect(240, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_49 = QtWidgets.QLabel(self.tab_14)
        self.label_49.setGeometry(QtCore.QRect(650, 240, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_41.setGeometry(QtCore.QRect(830, 240, 301, 31))
        self.lineEdit_41.setText("")
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_42.setGeometry(QtCore.QRect(830, 370, 301, 31))
        self.lineEdit_42.setText("")
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.label_50 = QtWidgets.QLabel(self.tab_14)
        self.label_50.setGeometry(QtCore.QRect(650, 110, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_43.setGeometry(QtCore.QRect(830, 110, 301, 31))
        self.lineEdit_43.setText("")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.label_51 = QtWidgets.QLabel(self.tab_14)
        self.label_51.setGeometry(QtCore.QRect(650, 370, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 551, 591))
        self.groupBox.setObjectName("groupBox")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(190, 130, 301, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(190, 210, 301, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(10, 210, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(190, 380, 301, 31))
        self.lineEdit_11.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(10, 390, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(190, 290, 301, 31))
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 300, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(180, 510, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(116, 329, 281, 31))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(600, 10, 551, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(40, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(170, 90, 341, 31))
        self.lineEdit_17.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(170, 40, 341, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(40, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(270, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(600, 230, 551, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(50, 120, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(50, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_14.setGeometry(QtCore.QRect(200, 50, 311, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(200, 260, 311, 31))
        self.lineEdit_16.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_13.setGeometry(QtCore.QRect(200, 120, 311, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(50, 50, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 190, 311, 31))
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(40, 260, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(6, 0, 1161, 651))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 100, 1141, 511))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_14.setGeometry(QtCore.QRect(830, 30, 181, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_26 = QtWidgets.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(90, 25, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_19.setGeometry(QtCore.QRect(260, 30, 351, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 100, 1141, 491))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_20.setGeometry(QtCore.QRect(256, 30, 391, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_27 = QtWidgets.QLabel(self.tab_8)
        self.label_27.setGeometry(QtCore.QRect(100, 25, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_15.setGeometry(QtCore.QRect(890, 30, 181, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_4.setGeometry(QtCore.QRect(6, 100, 1141, 491))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_21.setGeometry(QtCore.QRect(276, 30, 381, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_28 = QtWidgets.QLabel(self.tab_9)
        self.label_28.setGeometry(QtCore.QRect(96, 25, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_16.setGeometry(QtCore.QRect(950, 30, 181, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.label_55 = QtWidgets.QLabel(self.tab_15)
        self.label_55.setGeometry(QtCore.QRect(370, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_7.setEnabled(True)
        self.tableWidget_7.setGeometry(QtCore.QRect(10, 140, 1161, 511))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(7)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(6, item)
        self.label_56 = QtWidgets.QLabel(self.tab_15)
        self.label_56.setGeometry(QtCore.QRect(380, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_15)
        self.label_57.setGeometry(QtCore.QRect(30, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_31.setGeometry(QtCore.QRect(710, 50, 241, 41))
        self.pushButton_31.setObjectName("pushButton_31")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_15)
        self.dateEdit.setGeometry(QtCore.QRect(240, 51, 301, 31))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setObjectName("dateEdit")
        self.tabWidget.addTab(self.tab_15, "")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 130, 75, 61))
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/App.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 300, 75, 61))
        self.pushButton_26.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon5)
        self.pushButton_26.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(20, 570, 75, 61))
        self.pushButton_37.setText("")
        self.pushButton_37.setIcon(icon)
        self.pushButton_37.setIconSize(QtCore.QSize(70, 55))
        self.pushButton_37.setObjectName("pushButton_37")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.tabWidget.tabBar().setVisible(False)
        self.Handel_Buttons()
        self.database()

        self.Show_Author()
        self.Show_Category()
        self.Show_Publisher()

        self.Show_All_Books()
        self.Show_All_Clients()
        self.Show_All_Operations()

        self.Show_Category_combox()
        self.Show_Author_combox()
        self.Show_Publisher_combox()

    def Handel_Buttons(self):
        self.pushButton_6.clicked.connect(self.Open_Day_To_Day_Tab)
        self.pushButton_2.clicked.connect(self.Open_Books_Tab)
        self.pushButton_26.clicked.connect(self.Open_Clients_Tab)
        self.pushButton_3.clicked.connect(self.Open_Users_Tab)
        self.pushButton_4.clicked.connect(self.Open_settings_Tab)
        self.pushButton_37.clicked.connect(self.Open_Monthly_sale_Tab)

        self.pushButton_15.clicked.connect(self.Add_Author)
        self.pushButton_14.clicked.connect(self.Add_Category)
        self.pushButton_16.clicked.connect(self.Add_Publisher)

        self.pushButton_7.clicked.connect(self.Add_New_Book)
        self.pushButton_10.clicked.connect(self.Search_Books)
        self.pushButton_8.clicked.connect(self.Edit_Books)
        self.pushButton_9.clicked.connect(self.Delete_Books)

        self.pushButton_22.clicked.connect(self.Add_New_Clients)
        self.pushButton_25.clicked.connect(self.Search_Client)
        self.pushButton_23.clicked.connect(self.Edit_Client)
        self.pushButton_24.clicked.connect(self.Delete_Client)

        self.pushButton_11.clicked.connect(self.Add_New_User)
        self.pushButton_13.clicked.connect(self.Login)
        self.pushButton_12.clicked.connect(self.Edit_User)

        self.pushButton.clicked.connect(self.Handel_Day_Operations)
        self.pushButton_30.clicked.connect(self.Print)
        self.pushButton_31.clicked.connect(self.Show_Monthly_Operations)
        
        self.pushButton_27.clicked.connect(self.Export_Day_Operations)
        self.pushButton_28.clicked.connect(self.Export_Books)
        self.pushButton_29.clicked.connect(self.Export_Clients)


    def database(self):
        self.cur.execute("""CREATE TABLE IF NOT EXISTS authors  (idauthors INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
        author_name VARCHAR (50) )""")
        self.cur.execute( """CREATE TABLE IF NOT EXISTS book (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, book_name VARCHAR (55),
         book_description VARCHAR (100), book_code VARCHAR (45), book_category VARCHAR (30), book_author VARCHAR (30), book_publisher VARCHAR (30),
        book_price  INT )""")
        self.cur.execute("""CREATE TABLE IF NOT EXISTS category ( idcategory INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, category_name VARCHAR (55))""")
        self.cur.execute("""CREATE TABLE IF NOT EXISTS clients ( client_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, client_name VARCHAR (70),
        client_address VARCHAR (60), client_phoneno    VARCHAR (30), client_nationalid VARCHAR (50), client_email VARCHAR (55),
        other_information VARCHAR (80) )""")
        self.cur.execute(""" CREATE TABLE IF NOT EXISTS dayoperations ( id INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
        book_name VARCHAR, client VARCHAR, transaction_type VARCHAR, amount INTEGER, date DATETIME, quatities INTEGER,
        price INTEGER )""")
        self.cur.execute( """ CREATE TABLE IF NOT EXISTS publisher ( idpublisher INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL, publisher_name INT (45) 
        )""")
        self.db.close()
 
    ######################################
    ########## opening tabs ##############
    def Open_Day_To_Day_Tab(self):
        self.tabWidget.setCurrentIndex(0)

    def Open_Books_Tab(self):
        self.tabWidget.setCurrentIndex(1)

    def Open_Clients_Tab(self):
        self.tabWidget.setCurrentIndex(2)

    def Open_Users_Tab(self):
        self.tabWidget.setCurrentIndex(3)

    def Open_settings_Tab(self):
        self.tabWidget.setCurrentIndex(4)

    def Open_Monthly_sale_Tab(self):
        self.tabWidget.setCurrentIndex(5)

    ######################################
    ##########Day operations #############
    def Handel_Day_Operations(self):
        book_title = self.lineEdit.text()
        client_name = self.lineEdit_25.text()
        price = self.spinBox_2.value()
        transaction_type = self.comboBox_2.currentText()
        quantities = self.spinBox.value()
        amount = quantities*price
        date = datetime.datetime.today()
    
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(''' INSERT INTO dayoperations (book_name, client,price, amount, transaction_type, date, quatities)
            VALUES(?, ?, ?, ?, ?, ?, ?)''', (book_title, client_name, price, amount, transaction_type, date, quantities))
        self.db.commit()
        self.statusbar.showMessage('New Sales Recorded Successfully')
        self.db.close()

        tran_date = (f'Transaction date {str(date)}')
        msg = "Ohms Publisher Limited\nReceipt for items purchased\n"
        name= f"Name = {client_name} \n"
        book = f"Book Title = {book_title} \n"
        Quantitie_sp = f"Quatities of items purchased ={quantities}\n"
        price_ = f"Book Price = {price} \n"
        sp = "--------------------------------------- \n"
        pk = "--------------------------------------- \n"
        amount = f"Total Price = #{amount}.00 \n"
        mp = "--------------------------------------- \n"
        dp =' \n'
        thank = "Thanks for your patronage\n"
        receipt = (msg+pk+name+book+Quantitie_sp+price_+sp+amount+mp+thank+dp+tran_date)
        self.textEdit_3.setPlainText(receipt)

        self.Show_All_Operations()
        self.lineEdit.setText('')
        self.lineEdit_25.setText('')
        self.spinBox.setValue(1)
        self.spinBox_2.setValue(1)

    def Show_All_Operations(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(''' SELECT book_name, client, Price, quatities, amount, transaction_type, date FROM dayoperations ''')
        data = self.cur.fetchall()
        #print(data)

        self.tableWidget.setRowCount(0)
        self.tableWidget.insertRow(0)
        for row, form in enumerate(data):
            for column, item in enumerate(form):
                self.tableWidget.setItem(row, column, QTableWidgetItem(str(item)))
                column +=1
            row_postion = self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_postion)
        self.db.close()

    def Show_Monthly_Operations(self):
        dates = self.dateEdit.text()
        Date = f"'{dates}%'"
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(f''' SELECT book_name, client, Price, quatities, amount, transaction_type, date FROM dayoperations WHERE date LIKE {Date}''' )
        data = self.cur.fetchall()
        #print(data)
        if data:
            self.tableWidget_7.setRowCount(0)
            for row_number, row_data in enumerate(data):
                #print(row_data)
                self.tableWidget_7.insertRow(row_number)
                for column_number, main_data in enumerate(row_data):
                    #print(main_data)
                    self.tableWidget_7.setItem(row_number, column_number, QTableWidgetItem(str(main_data)))
            self.db.close()
            self.statusbar.showMessage(f'Record for {dates}')
        else:
            self.statusbar.showMessage('Record not found')

    ######################################
    ########## settings   ################
    def Add_Category(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        category_name = self.lineEdit_19.text()
        self.cur.execute('''INSERT INTO category (category_name) VALUES (?)''', (category_name,))

        self.db.commit()
        self.statusbar.showMessage(f'New Category {category_name} added')
        self.lineEdit_19.setText(' ')
        self.Show_Category()
        self.Show_Category_combox()
        self.lineEdit_19.setText('')

    def Show_Category(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT category_name FROM category''')
        data = self.cur.fetchall()

        if data:
            self. tableWidget_2.setRowCount(0)
            self.tableWidget_2.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget_2.setItem(
                        row, column, QTableWidgetItem(str(item)))
                    column += 1
                row_position = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_position)

    def Add_Author(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        authorname = self.lineEdit_20.text()
        self.cur.execute('''INSERT INTO authors (author_name) VALUES (?) ''', (authorname,))
        self.db.commit()
        self.lineEdit_20.setText('')
        self.statusbar.showMessage(f'New Author {authorname} added')

        self.Show_Author()
        self.Show_Author_combox()

    def Show_Author(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute('''SELECT author_name FROM authors''')
        data = self.cur.fetchall()
        if data:
            self. tableWidget_3.setRowCount(0)
            self.tableWidget_3.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget_3.setItem(
                        row, column, QTableWidgetItem(str(item)))
                    column += 1
                row_position = self.tableWidget_3.rowCount()
                self.tableWidget_3.insertRow(row_position)

    def Add_Publisher(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        publish_name = self.lineEdit_21.text()
        self.cur.execute(''' INSERT INTO publisher (publisher_name) VALUES (?)''', (publish_name,))

        self.db.commit()
        self.lineEdit_21.setText('')
        self.statusbar.showMessage(f'New Publisher {publish_name} added')

        self.Show_Publisher()
        self.Show_Publisher_combox()

    def Show_Publisher(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT publisher_name FROM publisher ''')
        data = self.cur.fetchall()

        if data:
            self. tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget_4.setItem(
                        row, column, QTableWidgetItem(str(item)))
                    column += 1
                row_position = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_position)

########## print receipt #####################
    def Print(self):
        self.editor = self.textEdit_3.document()
        printer = QPrinter(QPrinter.HighResolution)
        dialog = QPrintDialog(printer, self)
        if dialog.exec_() == QPrintDialog.Accepted:
            self.editor.print_(printer)

######################################
########## books #####################
    def Show_All_Books(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT book_code, book_name, book_description, book_category, book_author, book_publisher, book_price FROM book ''')
        data = self.cur.fetchall()

        #print(data)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_5.insertRow(0)
        for row, form in enumerate(data):
            for column, item in enumerate(form):
                self.tableWidget_5.setItem(row, column, QTableWidgetItem(str(item)))
                column +=1
            row_position = self.tableWidget_5.rowCount()
            self.tableWidget_5.insertRow(row_position)
        self.db.close()

    def Add_New_Book(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        book_title = self.lineEdit_3.text()
        book_description =self.textEdit.toPlainText()
        book_code = self.lineEdit_2.text()
        book_category = self.comboBox_3.currentText()
        book_author = self.comboBox_4.currentText()
        book_publisher = self.comboBox_5.currentText()
        book_price = self.lineEdit_4.text()

        self.cur.execute(''' INSERT INTO book (book_name, book_description,book_code, book_category, book_author, 
        book_publisher, book_price) VALUES(?,?,?,?,?,?,?)
        ''', (book_title, book_description,book_code, book_category, book_author, book_publisher, book_price))
        self.db.commit()
        self.statusbar.showMessage(f'New Book {book_title} Added')

        self.lineEdit_3.setText('')
        self.textEdit.setPlainText('')
        self.lineEdit_2.setText('')
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.lineEdit_4.setText('')
        self.Show_All_Books()


    def Search_Books(self):

        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        book_title = self.lineEdit_8.text()
        self.cur.execute('''SELECT * FROM book WHERE book_name = ? ''',[(book_title)])
        data = self.cur.fetchone()
        if data :
            #print(data)
            self.lineEdit_5.setText(data[1])
            self.textEdit_2.setPlainText(data[2])
            self.lineEdit_6.setText(data[3])
            self.comboBox_6.setCurrentText(data[4])
            self.comboBox_7.setCurrentText(data[5])
            self.comboBox_8.setCurrentText(data[6])
            self.lineEdit_7.setText(str(data[7]))
        else:
            QMessageBox.warning(self, 'Error', f"Book title {book_title} not found", QMessageBox.Ok)
            self.statusbar.showMessage('Please enter the correct book title')


    def Edit_Books(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        book_title = self.lineEdit_5.text()
        book_description =self.textEdit_2.toPlainText()
        book_code = self.lineEdit_6.text()
        book_category = self.comboBox_6.currentText()
        book_author = self.comboBox_7.currentText()
        book_publisher = self.comboBox_8.currentText()
        book_price = self.lineEdit_7.text()
        search_book_title =self.lineEdit_8.text()

        self.cur.execute('''
            UPDATE book SET book_name=?, book_description=?, book_code=?, book_category=?, book_author=?, book_publisher=?, book_price=? WHERE book_name =? 
        ''',(book_title, book_description, book_code, book_category, book_author, book_publisher, book_price, search_book_title))
        self.db.commit()
        self.statusbar.showMessage('book updated')
        self.Show_All_Books()
        self.db.close()

        self.lineEdit_8.setText('')
        self.lineEdit_5.setText('')
        self.textEdit_2.setPlainText('')
        self.lineEdit_6.setText('')
        self.lineEdit_7.setText('')

    def Delete_Books(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        book_title = self.lineEdit_8.text()
        warning = QMessageBox.warning(self, 'Delete Book', "Are you sure you want to delete this book", QMessageBox.Yes | QMessageBox.No )
        if warning == QMessageBox.Yes:
            sql = '''DELETE FROM book WHERE book_name = ?'''
            self.cur.execute(sql, [(book_title)])
            self.db.commit()
            self.statusbar.showMessage('Book Deleted')
            self.db.close()
            self.Show_All_Books()
            self.lineEdit_5.setText('')
        self.textEdit_2.setPlainText('')
        self.lineEdit_6.setText('')
        self.lineEdit_7.setText('')
    ######################################
    ########## clients ####################
    def Show_All_Clients(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(''' SELECT client_ID, client_name, client_address,  client_phoneno, client_nationalid,
                             client_email, other_information FROM clients ''')
        data = self.cur.fetchall()
        #print(data)
        self.tableWidget_6.setRowCount(0)
        self.tableWidget_6.insertRow(0)
        for row, form in enumerate(data):
            for column, item in enumerate(form):
                self.tableWidget_6.setItem(
                    row, column, QTableWidgetItem(str(item)))
                column += 1
            row_position = self.tableWidget_6.rowCount()
            self.tableWidget_6.insertRow(row_position)
        self.db.close()

    def Add_New_Clients(self):
        client_name = self.lineEdit_23.text()
        client_email = self.lineEdit_24.text()
        client_nationalid = self.lineEdit_29.text()
        client_phoneno = self.lineEdit_38.text()
        client_address = self.lineEdit_39.text()
        other_information = self.lineEdit_40.text()

        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute('''INSERT INTO clients (client_name, client_email, client_nationalid, client_phoneno, client_address, 
                            other_information) VALUES(?,?,?,?,?,?) ''', (client_name, client_email, 
                            client_nationalid, client_phoneno, client_address, other_information))
        self.db.commit()
        self.db.close()
        self.statusbar.showMessage(f'New Client {client_name} Added Successfully')
        self.Show_All_Clients()

        self.lineEdit_23.setText('')
        self.lineEdit_24.setText('')
        self.lineEdit_29.setText('')
        self.lineEdit_38.setText('')
        self.lineEdit_39.setText('')
        self.lineEdit_40.setText('')

    def Search_Client(self):
        client_unique_id = self.lineEdit_28.text()
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute( '''SELECT * FROM clients WHERE client_ID = ?''' , [client_unique_id])
        data = self.cur.fetchone()
        #print(data)
        if data:
            self.lineEdit_22.setText(data[1])
            self.lineEdit_26.setText(data[5])
            self.lineEdit_30.setText(data[4])
            self.lineEdit_43.setText(data[3])
            self.lineEdit_41.setText(data[2])
            self.lineEdit_42.setText(data[6])

        else:
            QMessageBox.warning(
                self, 'Error', f" client national ID {client_unique_id} not found", QMessageBox.Ok)
            self.statusbar.showMessage('Please enter the correct client national ID')

    def Edit_Client(self):
        client_original_unique_id = self.lineEdit_28.text()
        client_name = self.lineEdit_22.text()
        client_email = self.lineEdit_26.text()
        client_national_id = self.lineEdit_30.text()
        client_phoneno = self.lineEdit_43.text()
        client_address = self.lineEdit_41.text()
        other_information = self.lineEdit_42.text()

        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute(''' UPDATE clients SET client_name = ?, client_email = ?, client_nationalid = ?, 
        client_phoneno = ?,  client_address = ?, other_information = ? WHERE client_ID = ? ''', 
        (client_name, client_email, client_national_id, client_phoneno, client_address, other_information, 
        client_original_unique_id))

        self.db.commit()
        self.db.close()
        self.statusbar.showMessage('Client Data Update')
        self.Show_All_Clients()
        self.lineEdit_28.setText('')
        self.lineEdit_22.setText('')
        self.lineEdit_26.setText('')
        self.lineEdit_30.setText('')
        self.lineEdit_43.setText('')
        self.lineEdit_41.setText('')
        self.lineEdit_42.setText('')

    def Delete_Client(self):
        client_original_unique_id = self.lineEdit_28.text()

        warning_message = QMessageBox.warning( self, "Delete Client", "Are you sure you want to delete this client?", QMessageBox.Yes | QMessageBox.No)
        if warning_message == QMessageBox.Yes:
            self.db = sqlite3.connect('ohms.db')
            self.cur = self.db.cursor()
            self.cur.execute('''DELETE FROM clients WHERE client_ID = ?''', [client_original_unique_id])
            self.db.commit()
            self.db.close()

            self.statusbar.showMessage('Client Deleted Successfully')
            self.Show_All_Clients()

            self.lineEdit_22.setText('')
            self.lineEdit_26.setText('')
            self.lineEdit_30.setText('')
            self.lineEdit_43.setText('')
            self.lineEdit_41.setText('')
            self.lineEdit_42.setText('')
    ######################################
    #####show settings data in UI#########
    def Show_Category_combox(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT category_name FROM category''')
        data = self.cur.fetchall()

        self.comboBox_3.clear()
        for category in data:
            #print(category[0])
            self.comboBox_3.addItem(category[0])
            self.comboBox_6.addItem(category[0])

    def Show_Author_combox(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT author_name FROM authors''')
        data = self.cur.fetchall()

        self.comboBox_4.clear()
        for category in data:
            self.comboBox_4.addItem(category[0])
            self.comboBox_7.addItem(category[0])

    def Show_Publisher_combox(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT publisher_name FROM publisher''')
        data = self.cur.fetchall()

        self.comboBox_5.clear()
        for category in data:
            self.comboBox_5.addItem(category[0])
            self.comboBox_8.addItem(category[0])
    
    #################################
    ########## users ################
    def Add_New_User(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        username = self.lineEdit_9.text()
        email = self.lineEdit_10.text()
        password = self.lineEdit_12.text()
        comfirm_password = self.lineEdit_11.text()

        if password == comfirm_password:
            self.cur.execute('''INSERT INTO users (user_name, user_email, user_password) VALUES (?,?,?)''', (username, email, password))
            self.db.commit()
            self.statusbar.showMessage('New User Added')
            self.lineEdit_9.setText('')
            self.lineEdit_10.setText('')
            self.lineEdit_12.setText('')
            self.lineEdit_11.setText('')

        else:
            self.label_30.setText('please add a valid password twice')

    def Login(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        username = self.lineEdit_18.text()
        password = self.lineEdit_17.text()
        self.cur.execute('''SELECT * FROM users''')
        data = self.cur.fetchall()
        for row in data:
            if username == row[1] and password == row[3]:
                #print(data)
                self.groupBox_4.setEnabled(True)
                self.lineEdit_18.setText("")
                self.lineEdit_17.setText("")
                self.statusbar.showMessage('Valid Username & Password')

                self.lineEdit_14.setText(row[1])
                self.lineEdit_13.setText(row[2])
                self.lineEdit_15.setText(row[3])
                
            else:
                self.statusbar.showMessage('Invalid Username or Password')

    def Edit_User(self):
        username = self.lineEdit_14.text()
        email = self.lineEdit_13.text()
        password = self.lineEdit_15.text()
        confirm_password = self.lineEdit_16.text()

        original_name = self.lineEdit_18.text()

        if password == confirm_password:
            self.db = sqlite3.connect('ohms.db')
            self.cur = self.db.cursor()

            self.cur.execute(''' UPDATE users SET user_name = ?, user_email = ?, user_password = ? WHERE user_name = ?''',
                             (username, email, password, original_name))
            self.db.commit()
            self.statusbar.showMessage('User Data Updated Successfully')

        else:
            print('make sure you enter your password correctly')

######################################
########## Export Data ###############
    def Export_Day_Operations(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()

        self.cur.execute('''SELECT book_name, client, Price, quatities, amount, transaction_type, date FROM dayoperations ''')
        data = self.cur.fetchall()

        wb = Workbook('C:/Exported file/Sale Record.xlsx')
        sheet1 = wb.add_worksheet()
        sheet1.write(0,0,'Book Title')
        sheet1.write(0,1,'Client Name')
        sheet1.write(0,2, 'Price')
        sheet1.write(0,3,'Quantities')
        sheet1.write(0,4,'Amount')
        sheet1.write(0,5,'Transaction Type')
        sheet1.write(0,6,'Date')

        row_number = 1
        for row in data:
            column_number = 0
            #print(row)
            for item in row:
                #print(item)
                sheet1.write(row_number,column_number, str(item))
                column_number +=1
            row_number +=1
        wb.close()
        self.statusbar.showMessage('Sale Record Exported Successfully')

    def Export_Books(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(''' SELECT book_code, book_name, book_description, book_category, book_author, book_publisher, book_price FROM book ''')
        data = self.cur.fetchall()

        wb = Workbook('C:/Exported file/All Books.xlsx')
        sheet1 = wb.add_worksheet()
        sheet1.write(0,0, 'Book Code')
        sheet1.write(0,1, 'Book Name')
        sheet1.write(0,2, 'Book Description')
        sheet1.write(0,3, 'Book Category')
        sheet1.write(0,4, 'Book Author')
        sheet1.write(0,5, 'Book Publisher')
        sheet1.write(0,6, 'Book price')

        row_number = 1
        for row in data:
            column_number = 0
            for item in row:
                sheet1.write(row_number,column_number, str(item))
                column_number +=1
            row_number +=1

        wb.close()
        self.statusbar.showMessage('Book Record Exported Successfully')


    def Export_Clients(self):
        self.db = sqlite3.connect('ohms.db')
        self.cur = self.db.cursor()
        self.cur.execute(''' SELECT client_ID, client_name, client_email, client_nationalid, client_phoneno, client_address, other_information FROM clients ''')
        data = self.cur.fetchall()

        wb = Workbook('C:/Exported file/All Clients.xlsx')
        sheet1 = wb.add_worksheet()
        sheet1.write(0,0, 'Client ID')
        sheet1.write(0,1, 'Client Name')
        sheet1.write(0,2, 'Client Email')
        sheet1.write(0,3, 'Client National ID')
        sheet1.write(0,4, 'Client Phone Number')
        sheet1.write(0,5, 'Client Address')
        sheet1.write(0,6, 'Other Information')

        row_number = 1
        for row in data:
            column_number = 0
            for item in row:
                sheet1.write(row_number,column_number, str(item))
                column_number +=1
            row_number +=1

        wb.close()
        self.statusbar.showMessage('Clients Record Exported Successfully')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Ohms Publisher Ltd"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quatities"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total Amount"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Transaction Type"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date"))
        self.pushButton.setText(_translate("MainWindow", "Complete Transaction"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Book Title"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Buy"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Buy On Credit"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Retrieve"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Free"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Promo"))
        self.label.setText(_translate("MainWindow", "Transaction Type"))
        self.label_2.setText(_translate("MainWindow", "Quantities"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Enter Client Name"))
        self.pushButton_27.setText(_translate("MainWindow", "Export Sale Record to Excel File"))
        self.label_53.setText(_translate("MainWindow", "SALES RECORD"))
        self.label_54.setText(_translate("MainWindow", "Ohms Publisher Ltd, Lagos Nigeria"))
        self.pushButton_30.setText(_translate("MainWindow", "Print Receipt"))
        self.label_38.setText(_translate("MainWindow", "Book Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Code"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Describtion"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book category"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book Author"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Publisher"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Book Price"))
        self.pushButton_28.setText(_translate("MainWindow", "Export Book to Excel File"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "All Books"))
        self.pushButton_7.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "Book Title"))
        self.label_4.setText(_translate("MainWindow", "Book Code"))
        self.label_5.setText(_translate("MainWindow", "Book Price"))
        self.label_6.setText(_translate("MainWindow", "Category"))
        self.label_7.setText(_translate("MainWindow", "Author"))
        self.label_8.setText(_translate("MainWindow", "Publisher"))
        self.label_37.setText(_translate("MainWindow", "Book Description"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Add New Book"))
        self.label_9.setText(_translate("MainWindow", "Publisher"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.label_10.setText(_translate("MainWindow", "Book Code"))
        self.label_11.setText(_translate("MainWindow", "Book Price"))
        self.label_12.setText(_translate("MainWindow", "Category"))
        self.label_13.setText(_translate("MainWindow", "Author"))
        self.label_14.setText(_translate("MainWindow", "Book Title"))
        self.pushButton_9.setText(_translate("MainWindow", "Delete"))
        self.pushButton_10.setText(_translate("MainWindow", "Search"))
        self.label_15.setText(_translate("MainWindow", "Book Title"))
        self.label_52.setText(_translate("MainWindow", "Book Description"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit or Delete A Book "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Unique ID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client Address"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Client Phone No"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Client National ID"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Client Email"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Other Information"))
        self.pushButton_29.setText(_translate("MainWindow", "Export Clients to Excel File"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "All Clients"))
        self.pushButton_22.setText(_translate("MainWindow", "Add New Client"))
        self.label_31.setText(_translate("MainWindow", "Client Name"))
        self.label_32.setText(_translate("MainWindow", "Client Email"))
        self.label_33.setText(_translate("MainWindow", "Client National ID"))
        self.label_46.setText(_translate("MainWindow", "Client Phone No"))
        self.label_47.setText(_translate("MainWindow", "Client Address"))
        self.label_48.setText(_translate("MainWindow", "Other Information"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Add New Client"))
        self.pushButton_25.setText(_translate("MainWindow", "Search"))
        self.label_43.setText(_translate("MainWindow", "Client Unique ID"))
        self.pushButton_23.setText(_translate("MainWindow", "Save Client Data"))
        self.label_34.setText(_translate("MainWindow", "Client National ID"))
        self.label_35.setText(_translate("MainWindow", "Client Email"))
        self.label_36.setText(_translate("MainWindow", "Client Name"))
        self.pushButton_24.setText(_translate("MainWindow", "Delete Client"))
        self.label_49.setText(_translate("MainWindow", "Client Address"))
        self.label_50.setText(_translate("MainWindow", "Client Phone No"))
        self.label_51.setText(_translate("MainWindow", "Other Information"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "Edit or Delete A Client "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Add New User"))
        self.label_16.setText(_translate("MainWindow", "User Name"))
        self.label_17.setText(_translate("MainWindow", "Email"))
        self.label_18.setText(_translate("MainWindow", "Confirm Password"))
        self.label_19.setText(_translate("MainWindow", "Password"))
        self.pushButton_11.setText(_translate("MainWindow", "Add User"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit User Information"))
        self.label_24.setText(_translate("MainWindow", "Password"))
        self.label_25.setText(_translate("MainWindow", "User Name"))
        self.pushButton_13.setText(_translate("MainWindow", "Login"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Edit Your Data"))
        self.label_20.setText(_translate("MainWindow", "Email"))
        self.label_23.setText(_translate("MainWindow", "Password"))
        self.label_22.setText(_translate("MainWindow", "User Name"))
        self.pushButton_12.setText(_translate("MainWindow", "Edit User Data"))
        self.label_21.setText(_translate("MainWindow", "Confirm Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category Name"))
        self.pushButton_14.setText(_translate("MainWindow", "Add New Category"))
        self.label_26.setText(_translate("MainWindow", "New Category Name"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Categories"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Author Name"))
        self.label_27.setText(_translate("MainWindow", "New Author Name"))
        self.pushButton_15.setText(_translate("MainWindow", "Add New Author"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Author"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pulisher Name"))
        self.label_28.setText(_translate("MainWindow", "New Publisher Name"))
        self.pushButton_16.setText(_translate("MainWindow", "Add New Publisher"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Publisher"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.label_55.setText(_translate("MainWindow", "SALES RECORD"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quatities"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total Amount"))
        item = self.tableWidget_7.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Transaction Type"))
        item = self.tableWidget_7.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date"))
        self.label_56.setText(_translate("MainWindow", "Ohms Publisher Ltd, Lagos Nigeria"))
        self.label_57.setText(_translate("MainWindow", "Retrieve Sales Record For"))
        self.pushButton_31.setText(_translate("MainWindow", "Click Here To Show Record"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Mainapp()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

